extends:
  - react-app
  - plugin:eslint-comments/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jest/recommended
  - plugin:prettier/recommended
  - prettier/react
parser: babel-eslint
plugins:
  - eslint-comments
  - jest
  - jsx-a11y
  - react
  - import
env:
  jest/globals: false
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  quote-props:
    - error
    - as-needed
    - unnecessary: true
      numbers: true
      keywords: true
  import/no-named-as-default-member:
    - error
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
overrides:
  - files:
      - 'config-overrides.js'
    rules:
      import/no-extraneous-dependencies: 0
      global-require: 0
  - files:
      - '**/__tests__/**/*.js?(x)'
      - '**/?(*.)+(spec|test).js?(x)'
    rules:
      no-unused-expressions: 0
    env:
      jest/globals: true
